### ISSUE TITLE
Stored properties cannot be marked potentially unavailable with @available

### ISSUE THREAD

**Issue by frios** [what3words/w3w-swift-components#2]
When compiling with target set to iOS 16, the following errors are generated:

Stored properties cannot be marked potentially unavailable with @available

See attached imag
![Screen Shot 2022-06-27 at 9 49 02 AM](https://user-images.githubusercontent.com/6867187/175994133-4142662f-9b31-47a7-91f3-29e90f080aee.png)
e

**Comment by dave-w3w** [comment]
This is fixed in version [v2.3.1].  Thanks for raising the issue.
