### ISSUE TITLE
Issue in Scrollview

### ISSUE THREAD

**Issue by ManojReddyIGP** [what3words/w3w-swift-components#3]
While trying to framing the textfield inside scrollview, suggestion wrapper not framing properly.
Outside the scrollview fine, but handling textfield inside scroll getting issue

**Comment by ManuCiao** [comment]
hi @ManojReddyIGP thanks for reporting this issue. We will open a ticket to fix this issue. We will keep you posted once it is done. Thanks

**Comment by dave-w3w** [comment]
Hello, can you please elaborate the exact issue you are seeing so we can reproduce it.  We placed the W3WAutoSuggestTextField into a UIScrollView and could not replicate any issues.

**Comment by ManojReddyIGP** [comment]
I am Placing W3WAutoSuggestTextField using storyboard in scrollview, that too am placing that textfield in bottom of screen
When we are placing the textfield top of the screen it was working fine, but in bottom of screen not
When using this in scrollview, wrapper is not scrolling with textfield as well.

**Comment by dave-w3w** [comment]
I believe I've replicated the issue.  It looks like under very specific conditions, the suggestions dropdown is placing itself in the coordinate space of the parent of the parent's view, and not it's immediate parent view. Will update when we have a fix.

**Comment by dave-w3w** [comment]
I believe we have a fix. It now needs to go through some rigorous QA before release.  It is currently in the `staging` branch if you would like to let us know if we managed to sort your issue. Otherwise, we’ll update again when we publish it.

**Comment by dave-w3w** [comment]
Sorry for the delay. The `v3.0.0` update should correct this issue.  Reopen this issue if it persists.
