### ISSUE TITLE
Memory Leak issue in W3WMapViewController

### ISSUE THREAD

**Issue by ulian-onua** [what3words/w3w-swift-components#7]
There is memory leak issue in a method that happens because self isn't passed as `[weak self]` in the closures in the method
 `public func set(_ w3w: W3WProtocolV3, language: String = W3WSettings.defaultLanguage)` of  `W3WMapViewController`.

![image](https://github.com/what3words/w3w-swift-components/assets/15073398/b3f6b609-6df7-4549-b6b8-f06b1a0bdba7)

I already prepared PR to fix that. https://github.com/what3words/w3w-swift-components/pull/6

**Comment by andycurriew3w** [comment]
Hi @ulian-onua ,

Many thanks for reporting the issue and submitting a PR. I have passed to our engineers to review and merge.

Andy

**Comment by ulian-onua** [comment]
@andycurriew3w thank you. I am looking forward to the review and merging these fixes.

**Comment by dave-w3w** [comment]
This has been merged, thanks!
